services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10051:10051"   # <- Porta padrão do servidor Zabbix
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - zbx-alertscripts:/usr/lib/zabbix/alertscripts
      - zbx-externalscripts:/usr/lib/zabbix/externalscripts
    healthcheck:
      test: ["CMD-SHELL", "zabbix_server -R config_cache_reload || exit 1"]
      timeout: 10s
      retries: 5
      start_period: 30s

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      zabbix-server:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_TZ: ${PHP_TZ}
      APACHE_LISTEN_PORT: 8080

  zabbix-agent:
    image: zabbix/zabbix-agent:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      zabbix-server:
        condition: service_healthy
    environment:
      ZBX_SERVER_HOST: zabbix-server
    healthcheck:
      test: ["CMD-SHELL", "zabbix_agentd -t agent.ping || exit 1"]
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    

volumes:
  db-data:
  zbx-alertscripts:
  zbx-externalscripts:
  grafana-data:
