services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - zbx-alertscripts:/usr/lib/zabbix/alertscripts
      - zbx-externalscripts:/usr/lib/zabbix/externalscripts
    healthcheck:
      test: ["CMD-SHELL", "zabbix_server -R config_cache_reload || exit 1"]
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db-data:
  zbx-alertscripts:
  zbx-externalscripts:
